### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by hlgr360**
- Added our API Style Guide which was compiled from a wide variety of existing style guides
- Added additional Api Management solutions

### CODE REVIEW

**Comment by Leventhan** [comment]
Here are a few comments:
- Please squash both commits into one commit
- API Umbrella already exists on the list
- "nodejs" -> "Node.js"

:blossom: :four_leaf_clover: :sunflower:

**Comment by Leventhan** [comment]
@hlgr360 Any updates?

**Comment by Leventhan** [comment]
@hlgr360 Any updates?

**Comment by hlgr360** [comment]
Sorry, I am buried under a ton of stuff. Apologies.

**Pull request merged**
