### PR TITLE
adding Apiary and Readme to the list

### PR DESCRIPTION
**Pull request by hashd**
Apiary and Readme are wonderful products based on API documentation. I might not have put them in the right place so please do suggest as appropriate.

### CODE REVIEW

**Comment by Leventhan** [comment]
Looks good, except do you mind if we put embedcurl at the bottom? Since it's more of a supplementary documentation tool.

**Comment by hashd** [comment]
Sure. I made those changes

**Comment by Leventhan** [comment]
I meant you should amend your previous commit. Each PR should only be one commit.

Do you mind if you squash your two commits into one commit with the message "adding Apiary and Readme to the list"? After that, we can merge your PR.

**Comment by Leventhan** [comment]
Sorry, also do you mind removing words like "beautiful and easy" from your description of readme.io? We should be neutral.

**Comment by hashd** [comment]
Neutral descriptions makes sense. Do check the changes now.

**Comment by Leventhan** [comment]
:confetti_ball: Merged. :confetti_ball: 

Future contributions are most welcome!

**Pull request merged**
